platform :ios, '16.0'

use_frameworks!
use_modular_headers!

target 'App\' do
  capacitor_pods
  
  # Firebase pods for notifications
  pod 'FirebaseCore'
  pod 'FirebaseMessaging'
  pod 'FirebaseAnalytics'
  
  # Additional Capacitor plugins
  pod 'CapacitorApp'
  pod 'CapacitorHaptics'
  pod 'CapacitorKeyboard'
  pod 'CapacitorStatusBar'
  pod 'CapacitorGeolocation'
  pod 'CapacitorPushNotifications'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end